version: '3.5'

services:
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
    - "1080:1080"
    - "1025:1025"

  rabbitmq:
    image: rabbitmq:management
    container_name: e-petitions_rabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: e-petitions-project-db
    image: postgres:latest
    environment:
      POSTGRES_DB : e-petitions-project-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      PGDATA: /data/e-petitions-project-db
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5435:5432"
  redis:
    image: redis:latest
    container_name: e-petitions-redis-db
    ports:
      - "6379:6379"
volumes:
  postgres-db:
    driver: local