version: '3.9'

services:
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
    - "1080:1080"
    - "1025:1025"

  rabbitmq:
    image: rabbitmq:management
    container_name: e-petitions_rabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
